// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.Data.SqlClient;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using DBOptimizedDotNet;

namespace DBOptimizedDotNet
{
    public partial class DboptimizationsContext
    {
        private DboptimizationsContextProcedures _procedures;

        public DboptimizationsContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new DboptimizationsContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public DboptimizationsContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class DboptimizationsContextProcedures
    {
        private readonly DboptimizationsContext _context;

        public DboptimizationsContextProcedures(DboptimizationsContext context)
        {
            _context = context;
        }

    }
}
